#define MY_PORT	9999

#define MAX_USERS	5
#define USER_BUFFER	1025

static const telnet_telopt_t telopts[] =
{
    //{ TELNET_TELOPT_BINARY,    	TELNET_WILL,	 TELNET_DO },
    { TELNET_TELOPT_ECHO,    	TELNET_WILL,	 TELNET_DONT },
	{ TELNET_TELOPT_NAWS,		TELNET_WILL,	TELNET_DO },
	{ TELNET_TELOPT_LINEMODE,	TELNET_WONT,	TELNET_DONT },
	//{ TELNET_TELOPT_COMPRESS2,	TELNET_WILL,	TELNET_DONT },
	//{ TELNET_TELOPT_XASCII, 	TELNET_WILL, 	TELNET_DO },
	{ -1, 0, 0 }
};
